routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('sections', 'SectionController');
Route::resource('programs', 'ProgramController');
Route::resource('competences', 'CompetenceController');
Route::post('/competences/add_element/', 'ApiController@competences_add')->name('competences_add');
Route::get('/programs/create/{id_program?}', 'ProgramController@create')->name('create_programs');
Route::resource('layouts', 'LayoutController');
Route::resource('teachers', 'TeacherController');
Route::resource('directions', 'DirectionController');
Route::post('/api/directions/', 'ApiController@directions_get')->name('api_directions_get');
Route::get('/api/sections/', 'ApiController@change_type_description')->name('api_change_type_description');
Route::get('/api/competence_get/', 'ApiController@competence_get')->name('competence_get');
Route::get('/programs/{id_pr}/edit/{id_sec}', 'ProgramController@edit_second')->name('edit_sections');
Route::put('/programs/update/{id_pl}', 'ProgramController@update_second')->name('update_second');
Route::post('/api/purpose_edit/', 'ProgramController@purpose_edit')->name('purpose_edit');
Route::post('/api/place_change/', 'ProgramController@place_change')->name('place_change');
Route::post('/api/hours_change/', 'ProgramController@hours_change')->name('hours_change');
//Route::post('/api/directions/levelStudies', 'ApiController@directions_levelStudies')->name('api_directions_levelStudies');
//Route::post('/api/directions/formStudies', 'ApiController@directions_formStudies')->name('api_directions_formStudies');

resources/views/admin/layout_add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Новый макет</div>

                <div class="card-body">
                    <form action="{{ route('layouts.store') }}" method="post">
                        <div class="form-group">
                            <div class="col-lg-6">
                                <label for="name" class="form-control-label">Наименование: </label>
                            </div>
                            <div class="col-lg-12">
                                <input type="text" id="name" name="name" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-group" id="context_sections">
                            <div class="col-lg-6">
                                <label for="sections" class="form-control-label">Содержание: </label>
                            </div>
                            <div class="col-lg-12">
                                <table class="col-lg-12 table-bordered table">
                                    <thead>
                                    <tr>
                                        <th>№</th>
                                        <th>Раздел</th>
                                        {{--<th>Удалить</th>--}}
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <th>1</th>
                                        <th>
                                            <select class="form-control select_sections" id="sections" onchange="select_cont(this.value, 1)" name="section_1">
                                                <option value="">Выберите раздел</option>
                                                @foreach($sections as $section)
                                                    <option value="{{$section->id}}">{{$section->name}}</option>
                                                @endforeach
                                            </select>
                                        </th>
                                    </tr>
                                    <tr id="last_tr">
                                        <th colspan="2" class="text-center">
                                            <a href="#" class="btn btn-success" id="add_section" data-num="2" data-sections="{{$sections}}">Добавить раздел</a>
                                        </th>
                                    </tr>
                                    </tbody>
                                </table>
                                <input type="hidden" name="sections_numbers" id="section_cont">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-4">
                                <label for="year" class="form-control-label">Год: </label>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" id="year" name="year" class="form-control" required>
                            </div>
                        </div>
                        {{ csrf_field() }}
                        <div class="form-actions form-group">
                            <div class="col-lg-4 push-lg-4">
                                <input type="submit" value="Сохранить" class="btn btn-primary">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/layout_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Макет</div>

                    <div class="card-body">
                        <form action="{{ route('layouts.update', $layout->id) }}" method="post">
                            <div class="form-group">
                                <div class="col-lg-6">
                                    <label for="name" class="form-control-label">Наименование: </label>
                                </div>
                                <div class="col-lg-12">
                                    <input type="text" id="name" name="name" class="form-control" required value="{{$layout->name}}">
                                </div>
                            </div>
                            <div class="form-group" id="context_sections">
                                <div class="col-lg-6">
                                    <label for="sections" class="form-control-label">Содержание: </label>
                                </div>
                                <div class="col-lg-12">
                                    <table class="col-lg-12 table-bordered table">
                                        <thead>
                                        <tr>
                                            <th>№</th>
                                            <th>Раздел</th>
                                            {{--<th>Удалить</th>--}}
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @php $m = 1; @endphp
                                        @foreach($sections_list as $section_list)
                                            <tr>
                                                <th>{{$m}}</th>
                                                <th>
                                                    <select class="form-control select_sections" id="sections" onchange="select_cont(this.value, {{$m}})" name="section_{{$m}}">
                                                        <option value="">Выберите раздел</option>
                                                        @foreach($sections as $section)
                                                            @if($section->id == $section_list->id)
                                                                <option value="{{$section->id}}" selected>{{$section->name}}</option>
                                                            @else
                                                                <option value="{{$section->id}}">{{$section->name}}</option>
                                                            @endif
                                                        @endforeach
                                                    </select>
                                                </th>
                                            </tr>
                                            @php $m++; @endphp
                                        @endforeach
                                        <tr id="last_tr">
                                            <th colspan="2" class="text-center">
                                                <a href="#" class="btn btn-success" id="add_section" data-num="2" data-sections="{{$sections}}">Добавить раздел</a>
                                            </th>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <input type="hidden" name="sections_numbers" id="section_cont">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-4">
                                    <label for="year" class="form-control-label">Год: </label>
                                </div>
                                <div class="col-lg-4">
                                    <input type="text" id="year" name="year" class="form-control" required value="{{$layout->year}}">
                                </div>
                            </div>
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="form-actions form-group">
                                <div class="col-lg-4 push-lg-4">
                                    <input type="submit" value="Сохранить" class="btn btn-primary">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/layout_show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Макет</div>
                    <div class="card-body">
                        <h4>{{$layout->name}} за {{$layout->year}} год состоит из разделов:</h4>
                        @if(count($sections) > 0)
                           <div style="padding: 36px 110px;">
                            @foreach($sections as $section)
                               {!! $section !!}
                            @endforeach
                           </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/layouts.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Макеты рабочих программ</div>

                    <div class="card-body">
                        <div class="btn-group" style="float: right;">
                            <a href="{{ route('layouts.create') }}" class=" btn btn-default">
                                Добавить макет
                            </a>
                        </div>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Название</th>
                                <th>Год</th>
                                <th style="text-align: right;">Функционал</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($layouts->count())
                                @foreach($layouts as $layout)
                                    <tr>
                                        <td>{{ $layout->name }}</td>
                                        <td>{{ $layout->year }}</td>
                                        <td style="text-align: right;">
                                            <a href="{{ route('layouts.show', $layout->id) }}" class="btn btn-primary">Просмотр</a>&nbsp; &nbsp;
                                            <a href="{{ route('layouts.edit', $layout->id) }}" class="btn btn-success">Редактирование</a>&nbsp; &nbsp;
                                            <a onclick="event.preventDefault(); document.getElementById('delete-product').submit();" href='#' class="btn btn-danger">Удаление</a>
                                            <form id="delete-product"
                                                  action="{{ route('layouts.destroy', ['id' => $layout->id]) }}"
                                                  method="POST"
                                                  style="display: none;"
                                            >
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/program_add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Новый раздел</div>

                    <div class="card-body">
                        <form action="{{ route('programs.store') }}" method="post">
                            <div class="form-group">
                                <div class="col-lg-6">
                                    <label for="name" class="form-control-label">Наименование дисциплины: </label>
                                </div>
                                <div class="col-lg-12">
                                    <input type="text" id="name" name="name" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-6">
                                    <label for="old_program" class="form-control-label">Исходная программа: </label>
                                </div>
                                <div class="col-lg-12">
                                    <select class="form-control content_direction" id="old_program" name="old_program">
                                        <option value="">Не выбрано</option>
                                        @foreach($programs as $program)
                                        @if($program->id == $old_program)
                                        <option value="{{$program->id}}" selected>{{$program->name}}</option>
                                        @else
                                        <option value="{{$program->id}}">{{$program->name}}</option>
                                        @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-6">
                                    <label for="form_studies" class="form-control-label">Форма обучения: </label>
                                </div>
                                <div class="col-lg-12">
                                    <select class="form-control content_direction" id="form_studies" data-href="{{ route('api_directions_get') }}">
                                        @foreach($form_studies as $form_study)
                                            <option value="{{$form_study->id}}">{{$form_study->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-6">
                                    <label for="level_studies" class="form-control-label">Уровень образования: </label>
                                </div>
                                <div class="col-lg-12">
                                    <select class="form-control content_direction" id="level_studies" data-href="{{ route('api_directions_get') }}">
                                        @foreach($level_studies as $level_study)
                                            <option value="{{$level_study->id}}">{{$level_study->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-6">
                                    <label for="faculty" class="form-control-label">Факультет: </label>
                                </div>
                                <div class="col-lg-12">
                                    <select class="form-control content_direction" id="faculty" data-href="{{ route('api_directions_get') }}">
                                        @foreach($faculties as $faculty)
                                            <option value="{{$faculty->id}}">{{$faculty->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-6">
                                    <label for="direction" class="form-control-label">Направление подготовки: </label>
                                </div>
                                <div class="col-lg-12">
                                    <select class="form-control" id="direction" name="direction">
                                        <option></option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-6">
                                    <label for="year" class="form-control-label">Год: </label>
                                </div>
                                <div class="col-lg-12 text">
                                    <input type="text" id="year" name="year" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-6">
                                    <label for="layout" class="form-control-label">Макет: </label>
                                </div>
                                <div class="col-lg-12">
                                    <select class="form-control content_direction" id="layout" name="layouts">
                                        @foreach($layouts as $layout)
                                            <option value="{{$layout->id}}">{{$layout->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-6">
                                    <label for="course" class="form-control-label">Курс: (введите только номера)</label>
                                </div>
                                <div class="col-lg-12 text">
                                    <input type="text" id="course" name="course" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-6">
                                    <label for="type" class="form-control-label">Тип дисциплины: </label>
                                </div>
                                <div class="col-lg-12">
                                    <select class="form-control content_direction" id="type" name="type">
                                        @foreach($types as $type)
                                        <option value="{{$type->id}}">{{$type->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            {{ csrf_field() }}
                            <div class="form-actions form-group">
                                <div class="col-lg-4 push-lg-4">
                                    <input type="submit" value="Сохранить" class="btn btn-primary">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/program_show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Рабочая программа</div>
                    <div class="card-body">
                        <h4>{{$layout->name}}</h4>
                        @if(count($sections) > 0)
                        <div class="form-group">
                            <div class="col-lg-6">
                                <label for="text" class="form-control-label">Содержание: </label>
                            </div>
                            <div class="col-lg-12 text"><!--общую сумму часов для каждой работы в отдельности -->
                                <textarea id='mytextarea' class="form-control" name="text" id="text" rows="10">
                                @foreach($sections as $section)
                                        {!! $section !!}
                                    @endforeach
                                </textarea>
                            </div>
                        </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/programs.blade.php
@extends('layouts.app')

@section('content')
    <div class="container" style="max-width: 1600px;">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Рабочие программы</div>

                    <div class="card-body">
                        <div class="btn-group" style="float: right;">
                            <a href="{{ route('programs.create') }}" class=" btn btn-default">
                                Добавить программу
                            </a>
                        </div>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Название</th>
                                <th>Направление подготовки</th>
                                <th>Год</th>
                                {{--<th>Исполнитель</th>--}}
                                <th style="text-align: right;">Функционал</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($programs->count())
                                @foreach($programs as $program)
                                    <tr>
                                        <td>{{ $program->name }}</td>
                                        <td>{{ $program->directions->name }}</td>
                                        <td>{{ $program->year }}</td>
                                        <td style="text-align: right;">
                                            <a href="{{ route('programs.show', $program->id) }}" class="btn btn-primary">Просмотр</a>&nbsp; &nbsp;
                                            <a href="{{ route('programs.edit', $program->id) }}" class="btn btn-success">Редактирование</a>&nbsp; &nbsp;
                                            <a onclick="event.preventDefault(); document.getElementById('delete-product_{{$program->id}}').submit();" href='#' class="btn btn-danger">Удаление</a>
                                            <form id="delete-product_{{$program->id}}"
                                                  action="{{ route('programs.destroy', ['id' => $program->id]) }}"
                                                  method="POST"
                                                  style="display: none;"
                                            >
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/section_show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Раздел</div>

                    <div class="card-body">
                        <h2>{{$section->name}}</h2>
                        {!! $section->description !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/teachers.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Преподаватели и дисциплины</div>

                    <div class="card-body">
                        <div class="btn-group" style="float: right;">
                            {{--<a href="{{ route('programs.create') }}" class=" btn btn-default">--}}
                                {{--Добавить программу--}}
                            {{--</a>--}}
                        </div>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>ФИО</th>
                                <th>Дисциплина</th>
                                <th>Год</th>
                                {{--<th>Исполнитель</th>--}}
                                <th style="text-align: right;">Функционал</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($programs->count())
                                @foreach($programs as $program)
                                    <tr>
                                        <td>{{ $program->name }}</td>
                                        <td>{{ $program->directions->name }}</td>
                                        <td>{{ $program->year }}</td>
                                        <td style="text-align: right;">
                                            <a href="{{ route('programs.show', $section->id) }}" class="btn btn-primary">Просмотр</a>&nbsp; &nbsp;
                                            <a href="{{ route('programs.edit', $section->id) }}" class="btn btn-success">Редактирование</a>&nbsp; &nbsp;
                                            <a onclick="event.preventDefault(); document.getElementById('delete-product').submit();" href='#' class="btn btn-danger">Удаление</a>
                                            <form id="delete-product"
                                                  action="{{ route('programs.destroy', ['id' => $section->id]) }}"
                                                  method="POST"
                                                  style="display: none;"
                                            >
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection