routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('sections', 'SectionController');
Route::resource('programs', 'ProgramController');
Route::resource('competences', 'CompetenceController');
Route::post('/competences/add_element/', 'ApiController@competences_add')->name('competences_add');
Route::get('/programs/create/{id_program?}', 'ProgramController@create')->name('create_programs');
Route::resource('layouts', 'LayoutController');
Route::resource('teachers', 'TeacherController');
Route::resource('directions', 'DirectionController');
Route::post('/api/directions/', 'ApiController@directions_get')->name('api_directions_get');
Route::get('/api/sections/', 'ApiController@change_type_description')->name('api_change_type_description');
Route::get('/api/competence_get/', 'ApiController@competence_get')->name('competence_get');
Route::get('/programs/{id_pr}/edit/{id_sec}', 'ProgramController@edit_second')->name('edit_sections');
Route::put('/programs/update/{id_pl}', 'ProgramController@update_second')->name('update_second');
Route::post('/api/purpose_edit/', 'ProgramController@purpose_edit')->name('purpose_edit');
Route::post('/api/place_change/', 'ProgramController@place_change')->name('place_change');
Route::post('/api/hours_change/', 'ProgramController@hours_change')->name('hours_change');
//Route::post('/api/directions/levelStudies', 'ApiController@directions_levelStudies')->name('api_directions_levelStudies');
//Route::post('/api/directions/formStudies', 'ApiController@directions_formStudies')->name('api_directions_formStudies');

app/Layout.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Layout extends Model
{
    protected $fillable = ['name', 'sections', 'year', 'created_at'];

    public function programs()
    {
        return $this->hasMany('App\Program', 'layout_id');
    }
}

app/Http/Controllers/LayoutController.php
<?php

namespace App\Http\Controllers;

use App\Layout;
use App\Program;
use App\Section;
use Illuminate\Http\Request;

class LayoutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.layouts', ['layouts' => Layout::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sections = Section::orderBy('name')->get();
        return view('admin.layout_add', ['sections' => $sections]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $m = 1;
        $n = $request->post('sections_numbers');
        $arr_section = [];
        while($m <= $n){
            $value = $request->post('section_'.$m);
            array_push($arr_section, $value);
            $m++;
        }
        $arr_section = json_encode($arr_section);

        $layout = Layout::create([
            'name' => $request->post('name'),
            'sections' => $arr_section,
            'year' => $request->post('year')
        ]);
        return redirect()->route('layouts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Layout  $layout
     * @return \Illuminate\Http\Response
     */
    public function show(Layout $layout)
    {
        $arr_sections = json_decode($layout->sections);
        $sections = [];
        foreach($arr_sections as $arr_section){
            $section_name = Section::find($arr_section)->description;
            array_push($sections, $section_name);
        }
        return view('admin.layout_show', ['layout' => $layout, 'sections' => $sections]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Layout  $layout
     * @return \Illuminate\Http\Response
     */
    public function edit(Layout $layout)
    {
        $sections_arr = Section::orderBy('name')->get();
        $arr_sections = json_decode($layout->sections);

        $sections_list = [];
        foreach($arr_sections as $arr_section){
            $section_name = Section::find($arr_section);
            array_push($sections_list, $section_name);
        }
        return view('admin.layout_edit', ['layout' => $layout, 'sections_list' => $sections_list, 'sections' => $sections_arr]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Layout  $layout
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Layout $layout)
    {
        $m = 1;
        $n = $request->post('sections_numbers');
        echo $n;
        $arr_section = [];
        while($m <= $n){
            $value = $request->post('section_'.$m);
            array_push($arr_section, $value);
            $m++;
        }
        $arr_section = json_encode($arr_section);
        $layout->name = $request->post('name');
        $layout->sections = $arr_section;
        $layout->year = $request->post('year');
        $layout->save();
        return redirect()->route('layouts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Layout $layout
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Layout $layout)
    {
        $layout -> delete();
        return redirect()->route('layouts.index');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Генератор рабочих программ</title>

    <!-- Scripts -->
    <script src='{{ asset('js/jquery-3.3.1.min.js') }}'></script>
    <script src='{{ asset('js/app.js') }}'></script>
    <script src="{{ asset('js/lib/tinymce/tinymce.min.js') }}"></script>
    <script src='{{ asset('js/scripts.js') }}'></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <style>
        #mytextarea_ifr{
            min-height: 500px;
        }
        .cont_type{
            display: none;
        }
        .competence_group, #text_description{
            display: none;
        }
    </style>

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Генератор рабочих программ
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    @auth
                    <ul class="navbar-nav mr-auto">
                        @if(Auth::user()->hasRole('ROLE_ADMIN'))
                        <li><a class="nav-link" href="{{ route('sections.index') }}">Разделы</a></li>
                        <li><a class="nav-link" href="{{ route('layouts.index') }}">Макеты</a></li>
                        <li><a class="nav-link" href="{{ route('competences.index') }}">Компетенции</a></li>
                        {{--<li><a class="nav-link" href="{{ route('teachers.index') }}">Преподаватели</a></li>--}}
                        @endif
                        @if(Auth::user()->hasRole('ROLE_TEACHER'))
                                <li><a class="nav-link" href="{{ route('programs.index') }}">Рабочие программы</a></li>
                        @endif
                    </ul>
                    @endauth
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Войти') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Регистрация') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Выйти') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script>

    </script>
</body>
</html>